import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-blue-950`}
      ><header className="h-[40px] p-[10px 10%]">
      <div className="flex justify-around">
            <h1 className="text-[18px] md:text-[27px] font-bold text-orange-400 underline font-cursive">Qaimudin</h1>
     <a className="text-[13px] md:text-[20px] font-bold text-orange-400" href="/">Home</a>
  <a className="text-[13px] md:text-[20px] font-bold text-orange-400" href="./About">About</a>
<a className="text-[13px] md:text-[20px] font-bold text-orange-400" href="./Contact">Contact</a>
</div>
 </header>

        {children}
      </body>
    </html>
  );
}
